---
name: deep_qlearning_decay_very_low_decay
type: deep_qlearning_decay
epsilon: 0.8
epsilon_start: 0.8
epsilon_end: 0.1
epsilon_decay: 80000
gamma: 0.98
initialization: xavier_uniform
loss: smooth_l1
optimizer:
  optimizer: adam
  weigth_decay: 0.0001
  learning_rate: 0.00025
